### PR TITLE
feat(coverAmbience): full rewrite

### LINKED ISSUE #18: Cover Ambience not supporting current spicetify theme player transparency
## Expected behavior
The cover art should be transparent according to the spicetify theme settings.

## Actual behavior
The cover art is opaque and covers the background image.

## Steps to reproduce
1. Install spicetify and Cover Ambience extension
2. Apply a theme that has player transparency settings (in our case bloom)
3. Play a song and observe the cover art

## Screenshots
With cover ambience : 
https://user-images.githubusercontent.com/92419665/223159492-5b15c124-e073-4467-abd2-a476f44d8c1f.mp4

Without cover ambience : 
https://user-images.githubusercontent.com/92419665/223159548-dc6266bb-bf58-4461-b264-ffa97e85cc28.mp4

### LINKED ISSUE #31: Cover Ambience not matching theme colors
Hey Im using the bloom theme i read the other closed issues regarding this it seems to have been solved but i think the bug has popped up again 
image
vs
image

### LINKED ISSUE #33: Cover Ambience causing floating progress bar when used with themes that move it
Hey! I'm sure this is just as much an issue with the theme itself as it is with the plugin, but I figured i'd mention it just in case -- when the plugin is enabled, it raises the progress bar 10 pixels above where an installed theme tells it to be. Have tried with a few different themes and the result is the same.

test

### PR DESCRIPTION
**Pull request by SunsetTechuila**
everything is ready, but the next version of spicetify is required

fixes #18
fixes #31
fixes #33

### CODE REVIEW

**Comment by SunsetTechuila** [comment]
there are also some type warnings, these will be fixed with the spicetify types update

**Comment by SunsetTechuila** [comment]
> the next version of spicetify is required

rn you can replace the wrapper to test the extension
https://github.com/spicetify/spicetify-cli/blob/master/jsHelper/spicetifyWrapper.js

**Comment by SunsetTechuila** [comment]
https://github.com/spicetify/spicetify-cli/releases/tag/v2.28.1

**Comment by SunsetTechuila** [comment]
@Theblockbuster1 hello! you have no plans to merge this, right?

**Comment by Theblockbuster1** [comment]
Hi @SunsetTechuila, I'm sorry about the delays, things got in the way. Thank you for the pull request, even though its closed by now lol. I'm quite unfamiliar with React/TypeScript, so I think that merging it would've been a problem for me to maintain myself anyway. I may get back into things and try implementing your bug fixes into the extension again, I'll see. Thanks again!

**Pull request closed without merging**
