### PR TITLE
Fix broken background transition in Cover Ambience

### PR DESCRIPTION
**Pull request by hf02**
Fixes the lack of a background animation by using a pesudo-element with a gradient mask. This gives the same result as before, but lets the background be animated again by setting it as a solid color.

https://user-images.githubusercontent.com/55464333/222860842-432a83fa-aea0-4188-bd38-581d4d05a491.mp4

### CODE REVIEW

**Comment by jazzathedev** [comment]
Oh I should have checked what this is before I made #13 .... this does fix what im talking about right? Adds the transition between colours? It does look like that from the video you linked...

**Comment by Aimarekin** [comment]
That's funny because I had just installed this extension and I was just going to fix this issue. My approach however was setting the --cover-color to a @property and transitioning it instead

**Comment by Theblockbuster1** [comment]
Thanks for this, seems to work well!

**Comment by Theblockbuster1** [comment]
Actually, after inspecting closer, the gradient seems to render strangely and inconsistently
image
the transition works well though.

This is what it looked like originally:
image

**Comment by Aimarekin** [comment]
> Actually, after inspecting closer, the gradient seems to render strangely and inconsistently image the transition works well though.
> 
> This is what it looked like originally: image

It's hard to notice, but after putting the images on top of each other, though the gradient looks fine, it's true there's more artifacts on the new one, though it's mostly unnoticeable.
An alternative would be to keep the old one and animate the variable instead, though I'm not sure if this can be done in CSS with @property as I mentioned. It'd be doable in code however

**Comment by Aimarekin** [comment]
>  An alternative would be to keep the old one and animate the variable instead, though I'm not sure if this can be done in CSS with @Property as I mentioned. It'd be doable in code however

Update: Doesn't seem like this can be done with pure CSS, at least not straight-up (I'm going to see if it can be done with CSS transitions on the variable). It could still be animated in the script.

**Comment by Theblockbuster1** [comment]
I've just worked a solution using [this](https://stackoverflow.com/a/51238406/11037661), I'll release it very soon

**Comment by hf02** [comment]
Ah, that's my bad for doing this while having a reduced blue light mode on.

Looking at it more closely, it seems that the color gradient uses dithering. I guess using the mask doesn't. Happy to see that you got a solution though.

**Comment by Theblockbuster1** [comment]
@hf02 it's okay, your contribution is still appreciated!

**Comment by Theblockbuster1** [comment]
Okay, done! 9956274
I used 2 layers which fade between each other to create the transition effect

**Pull request merged**
